from typing import Optional
from pathlib import Path
import requests

DEFAULT_POSITIVE = "A photorealistic real-world dashcam video, highly detailed, cinematic lighting."
DEFAULT_NEGATIVE = "video game, CGI, CARLA simulation, low quality"

def generate_realistic_video(params: dict) -> bytes:
    """
    Calls the video generation API with a reference video and generation parameters.

    Args:
        params: {
            "input_reference": str,   # path to the .mp4 reference file
            "prompt": str,
            "negative_prompt": str,   # optional
            "size": str,              # e.g. "1024x512"
            "num_frames": int,
            "fps": int,
        }

    Returns:
        Raw video bytes (save with open(..., "wb").write(result))
    """
    url = params.get("url", "http://localhost:8000/v1/videos/sync")

    # keep track of output - we need to read it and return 1 frame
    response = requests.post(
        url,
        data=params,
    )

    response.raise_for_status()
    return response.content # raw generated bytes

def generate_request_params(
        num_frames: int = 20, 
        fps: int = 20, 
        size: str = "1024x512",
        input_reference: str = "",
        prompts : tuple = (DEFAULT_POSITIVE, DEFAULT_NEGATIVE),
    ) -> dict:
    
    return {
        "input_reference": input_reference,
        "prompt": prompts[0],
        "negative_prompt": prompts[1],
        "size": size,
        "num_frames": num_frames,
        "fps": fps,
    }